baseurl = "https://eternallogger.com/"
languageCode = "zh"
title = "樵志札記"
paginate = 20
theme = "casper"
Copyright = "All rights reserved - 2017"
isCJKLanguage = true
canonifyurls = true
buildDrafts = false
buildFuture = false

[params]
	author= "黃樵志"
	description = "數位時代的緩步生活"
	authorlocation = "Taipei, Taiwan"
	cover = "images/cover.jpg"
	logo = "images/logo.png"
 	twitterName = "eternallogger"
	facebookName = "eternallogger"
	# linkedinName = ""
	googleAnalyticsUserID = "UA-43093696-4"
	hideHUGOSupport = false

[blackfriday]

[[menu.main]]
	name = "札記封面"
	weight = 1
	identifier = "blog"
	url = "/"

[[menu.main]]
	name = "旅遊紀行"
	weight = 2
	identifier = "travel"
	url = "/tags/travel"

[[menu.main]]
	name = "科技雜談"
	weight = 3
	identifier = "technology"
	url = "/tags/technology"

[[menu.main]]
	name = "關於樵志"
	weight = 4
	identifier = "about"
	url = "/about"

[[menu.main]]
	name = "» 訂閱《樵志小報》"
	weight = 5
	identifier = "newsletter"
	url = "https://tinyletter.com/eternallogger"